### PR TITLE
Add support for AppCompatActivity

### PR DESCRIPTION
**Pull request by jromero**
The purpose of this PR is to add support for AppCompatActivity. It should be as simple as replacing an import from `import me.zhanghai.patternlock.SetPatternActivity;` to `import me.zhanghai.patternlock.appcompat.SetPatternActivity`.

Due to the nature of the implementation some of the methods need to be changed from protected to public. Such methods are `onForgotPassword`, `onCancel`, etc.

### CODE REVIEW

**Comment by zhanghai** [comment]
Thank you very much for this PR, very clean and helpful.

However, since everyone should be using appcompat nowadays, the original update I planned for this library is to update all activities to extend from AppCompatActivity, and I'll also restart from the 6.0.1 source of `LockPatternView` for a Material Design appearance.

I'll implement such update when I have time (should be about 2 weaks later after my final), so this PR won't be merged, but I'll keep it open till I've done the update for those who may be interested during such period of time.

**Comment by zhanghai** [comment]
Failing to resist the temptation, I've just done the migration to AppCompatActivity, and the sample is also heavily updated, although the 6.0.1 LockPatternView has not been ported yet.

Since the equivalent of this PR has been implemented, I'm closing it now.

**Comment by zhanghai** [comment]
The Material Design LockPatternView has been backported now.

**Comment by jromero** [comment]
Nice job! Much appreciated. The design definitely looks better. I'll move over to 2.0 here in a bit.

**Pull request closed without merging**
